spring:
   application:
      name: site
#spring.config.      
   config:
      use-legacy-processing: true
#spring.profiles.
   profiles:
      active: localhost
#spring.devtools.      
   devtools:
      livereload:
         enabled: true
      restart:
         enabled: true
#spring.datasource.
   datasource:
      hikari:
         driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
         jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/site_db
         username: site_db_user
         password: site_db_user
         pool-name: pool-site_db
         auto-commit: false
         connection-test-query: SELECT 1
         maximum-pool-size: 10
         transaction-isolation: TRANSACTION_READ_UNCOMMITTED #트랜잭션 격리수준 설정 
#spring.thymeleaf.        
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
log:
  path: C:\dev\using_spring\log     
---

spring:
 profiles:
  active: development
 devtools:
  livereload:
   enabled: true
  restart:
   enabled: true
 datasource: # db 설정
  hikari:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mariadb://129.154.54.184/site_db
    username: site_db_user
    password: ENC(hHlRGPY5S6eHiSK2yiqlqMneBXmWMy8Eqc72Z6au7cEYuqr/oI7FA30f2Ak9kcOW)
    pool-name: pool-site_db
    connection-test-query: SELECT 1
    maximum-pool-size: 10
    transaction-isolation: TRANSACTION_READ_UNCOMMITTED #트랜잭션 격리수준 설정 
#spring.thymeleaf.
 thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
--- 
server:
  port: 8088 
logging:
  config: classpath:log4j2-config.xml
log:
  path: /server/using-spring/logs
jasypt:
  encryptor: 
    bean: encryptor
