spring:
  profiles:
    active: dev
  application:
    name: site
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
#spring.datasource.      
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: ENC(hqSQkjdNOzsAR0I1ohAIQHudxfTIHvy0zji6q1kP+IHP72dt4VDha5Tcf5r56nL43nnPvIhpW1vky38YOoU6kudd1B16lCFfGP2m4JdpwzADrTBZLHvmY2nGqQel0urX)
      username: ENC(fSS0e3iLnYMrMVZWiogsT9nPtrHc0rbArlO+WWnY+huYtKKuHjxhLUeq3CmeA+dG)
      password: ENC(fSS0e3iLnYMrMVZWiogsT9nPtrHc0rbArlO+WWnY+huYtKKuHjxhLUeq3CmeA+dG)
      pool-name: pool-site_db
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED #트랜잭션 격리수준 설정
#spring.thymeleaf.
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    
server:
  port: 8088 
logging:
  config: classpath:log4j2-config.xml
log:
  path: /server/using-spring/logs
mail:
  addr: ENC(JK6YzbX76xC+2taysLS4QTLCrrI45pbSEyvxqqMh+58LFM5a1Yhtd2tzEYsfIcbJ4nI64SwztLTs+4kKCwYEzQ==)
  pwd: ENC(xfshyoX2mg1psKI9Q02gNGiDBDDg/h+/jDd9W5HYsB/qja99kIRIQ8yiU+WDkIepO6jxb/fiWvLeItOKBbeUzQ==)  